/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { ImpressionsDto } from '../models';
/**
 * ImpressionsApi - axios parameter creator
 * @export
 */
export const ImpressionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} slug 
         * @param {ImpressionsDto} impressionsDto Impression book
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        impressions: async (slug: string, impressionsDto: ImpressionsDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'slug' is not null or undefined
            assertParamExists('impressions', 'slug', slug)
            // verify required parameter 'impressionsDto' is not null or undefined
            assertParamExists('impressions', 'impressionsDto', impressionsDto)
            const localVarPath = `/impressions/impressions/{slug}`
                .replace(`{${"slug"}}`, encodeURIComponent(String(slug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(impressionsDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ImpressionsApi - functional programming interface
 * @export
 */
export const ImpressionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ImpressionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} slug 
         * @param {ImpressionsDto} impressionsDto Impression book
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async impressions(slug: string, impressionsDto: ImpressionsDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.impressions(slug, impressionsDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ImpressionsApi.impressions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ImpressionsApi - factory interface
 * @export
 */
export const ImpressionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ImpressionsApiFp(configuration)
    return {
        /**
         * 
         * @param {string} slug 
         * @param {ImpressionsDto} impressionsDto Impression book
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        impressions(slug: string, impressionsDto: ImpressionsDto, options?: any): AxiosPromise<void> {
            return localVarFp.impressions(slug, impressionsDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ImpressionsApi - object-oriented interface
 * @export
 * @class ImpressionsApi
 * @extends {BaseAPI}
 */
export class ImpressionsApi extends BaseAPI {
    /**
     * 
     * @param {string} slug 
     * @param {ImpressionsDto} impressionsDto Impression book
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImpressionsApi
     */
    public impressions(slug: string, impressionsDto: ImpressionsDto, options?: RawAxiosRequestConfig) {
        return ImpressionsApiFp(this.configuration).impressions(slug, impressionsDto, options).then((request) => request(this.axios, this.basePath));
    }
}

