version: "3"
services:
  backend-app:
    container_name: backend
    restart: always
    ports:
      - "8080:7777"
    build:
      dockerfile: ./apps/backend/Dockerfile
    env_file:
      - ./apps/backend/.env
