/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ActivityItem } from './activity-item';

/**
 *
 * @export
 * @interface Activity
 */
export interface Activity {
  /**
   * Active date
   * @type {string}
   * @memberof Activity
   */
  date: string;
  /**
   * Active count
   * @type {number}
   * @memberof Activity
   */
  count: number;
  /**
   * Active level
   * @type {number}
   * @memberof Activity
   */
  level: number;
  /**
   * List of activities
   * @type {Array<ActivityItem>}
   * @memberof Activity
   */
  activities: Array<ActivityItem>;
}
