/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AdminInfoByIdOutputCount } from './admin-info-by-id-output-count';
// May contain unused imports in some cases
// @ts-ignore
import { AdminInfoByIdOutputReviewInner } from './admin-info-by-id-output-review-inner';
// May contain unused imports in some cases
// @ts-ignore
import { FeaturedOutputRelatedGenresInner } from './featured-output-related-genres-inner';

/**
 * 
 * @export
 * @interface AdminInfoByIdOutput
 */
export interface AdminInfoByIdOutput {
    /**
     * 
     * @type {boolean}
     * @memberof AdminInfoByIdOutput
     */
    'visible': boolean;
    /**
     * 
     * @type {string}
     * @memberof AdminInfoByIdOutput
     */
    'ebook': string;
    /**
     * 
     * @type {string}
     * @memberof AdminInfoByIdOutput
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof AdminInfoByIdOutput
     */
    'popularity': number;
    /**
     * 
     * @type {number}
     * @memberof AdminInfoByIdOutput
     */
    'pages': number;
    /**
     * 
     * @type {AdminInfoByIdOutputCount}
     * @memberof AdminInfoByIdOutput
     */
    '_count': AdminInfoByIdOutputCount;
    /**
     * 
     * @type {Array<AdminInfoByIdOutputReviewInner>}
     * @memberof AdminInfoByIdOutput
     */
    'review': Array<AdminInfoByIdOutputReviewInner>;
    /**
     * 
     * @type {number}
     * @memberof AdminInfoByIdOutput
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof AdminInfoByIdOutput
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof AdminInfoByIdOutput
     */
    'picture': string;
    /**
     * 
     * @type {string}
     * @memberof AdminInfoByIdOutput
     */
    'author': string;
    /**
     * 
     * @type {Array<FeaturedOutputRelatedGenresInner>}
     * @memberof AdminInfoByIdOutput
     */
    'genres': Array<FeaturedOutputRelatedGenresInner>;
}

