/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BookTemplate } from './book-template';

/**
 * 
 * @export
 * @interface BookTemplateCatalogOutput
 */
export interface BookTemplateCatalogOutput {
    /**
     * can load more
     * @type {boolean}
     * @memberof BookTemplateCatalogOutput
     */
    'canLoadMore': boolean;
    /**
     * total pages
     * @type {number}
     * @memberof BookTemplateCatalogOutput
     */
    'totalPages': number;
    /**
     * book template
     * @type {Array<BookTemplate>}
     * @memberof BookTemplateCatalogOutput
     */
    'data': Array<BookTemplate>;
}

