/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FeaturedOutputRecommendationsInner } from './featured-output-recommendations-inner';

/**
 * 
 * @export
 * @interface ByIdOutput
 */
export interface ByIdOutput {
    /**
     * 
     * @type {Array<FeaturedOutputRecommendationsInner>}
     * @memberof ByIdOutput
     */
    'majorBooks': Array<FeaturedOutputRecommendationsInner>;
    /**
     * 
     * @type {number}
     * @memberof ByIdOutput
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ByIdOutput
     */
    'name': string;
}

