/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { OutputChapter } from './output-chapter';

/**
 *
 * @export
 * @interface EbookByIdOutput
 */
export interface EbookByIdOutput {
  /**
   * book title
   * @type {string}
   * @memberof EbookByIdOutput
   */
  title: string;
  /**
   * book picture
   * @type {string}
   * @memberof EbookByIdOutput
   */
  picture: string;
  /**
   * book file
   * @type {Array<string>}
   * @memberof EbookByIdOutput
   */
  file: Array<string>;
  /**
   * book chapters
   * @type {Array<OutputChapter>}
   * @memberof EbookByIdOutput
   */
  chapters: Array<OutputChapter>;
}
