/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FeaturedOutputRecommendationsInner } from './featured-output-recommendations-inner';
// May contain unused imports in some cases
// @ts-ignore
import { FeaturedOutputRelatedGenresInner } from './featured-output-related-genres-inner';

/**
 * 
 * @export
 * @interface FeaturedOutput
 */
export interface FeaturedOutput {
    /**
     * 
     * @type {Array<FeaturedOutputRelatedGenresInner>}
     * @memberof FeaturedOutput
     */
    'relatedGenres': Array<FeaturedOutputRelatedGenresInner>;
    /**
     * 
     * @type {Array<FeaturedOutputRecommendationsInner>}
     * @memberof FeaturedOutput
     */
    'recommendations': Array<FeaturedOutputRecommendationsInner>;
    /**
     * 
     * @type {Array<FeaturedOutputRecommendationsInner>}
     * @memberof FeaturedOutput
     */
    'popularBooks': Array<FeaturedOutputRecommendationsInner>;
    /**
     * 
     * @type {Array<FeaturedOutputRecommendationsInner>}
     * @memberof FeaturedOutput
     */
    'bestSellingBooks': Array<FeaturedOutputRecommendationsInner>;
    /**
     * 
     * @type {Array<FeaturedOutputRecommendationsInner>}
     * @memberof FeaturedOutput
     */
    'newReleases': Array<FeaturedOutputRecommendationsInner>;
}

