/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ImpressionDto
 */
export interface ImpressionDto {
    /**
     * 
     * @type {number}
     * @memberof ImpressionDto
     */
    'rating': number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ImpressionDto
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ImpressionDto
     */
    'comment'?: string;
}

