/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { PayloadChapter } from './payload-chapter';

/**
 *
 * @export
 * @interface PayloadEBook
 */
export interface PayloadEBook {
  /**
   *
   * @type {number}
   * @memberof PayloadEBook
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof PayloadEBook
   */
  title: string;
  /**
   *
   * @type {Array<PayloadChapter>}
   * @memberof PayloadEBook
   */
  chapters: Array<PayloadChapter>;
}
