/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UnfoldOutputImagesInner
 */
export interface UnfoldOutputImagesInner {
    /**
     * 
     * @type {string}
     * @memberof UnfoldOutputImagesInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UnfoldOutputImagesInner
     */
    'href': string;
    /**
     * 
     * @type {string}
     * @memberof UnfoldOutputImagesInner
     */
    'mimeType': string;
    /**
     * 
     * @type {string}
     * @memberof UnfoldOutputImagesInner
     */
    'data': string;
}

