/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserCatalogOutputDataInnerCount } from './user-catalog-output-data-inner-count';
// May contain unused imports in some cases
// @ts-ignore
import { UserCatalogOutputDataInnerSelectedGenresInner } from './user-catalog-output-data-inner-selected-genres-inner';
// May contain unused imports in some cases
// @ts-ignore
import { UserCatalogOutputDataInnerStatisticsInner } from './user-catalog-output-data-inner-statistics-inner';

/**
 * 
 * @export
 * @interface UserCatalogOutputDataInner
 */
export interface UserCatalogOutputDataInner {
    /**
     * 
     * @type {string}
     * @memberof UserCatalogOutputDataInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UserCatalogOutputDataInner
     */
    'email': string;
    /**
     * 
     * @type {Array<UserCatalogOutputDataInnerSelectedGenresInner>}
     * @memberof UserCatalogOutputDataInner
     */
    'selectedGenres': Array<UserCatalogOutputDataInnerSelectedGenresInner>;
    /**
     * 
     * @type {Array<UserCatalogOutputDataInnerStatisticsInner>}
     * @memberof UserCatalogOutputDataInner
     */
    'statistics': Array<UserCatalogOutputDataInnerStatisticsInner>;
    /**
     * 
     * @type {UserCatalogOutputDataInnerCount}
     * @memberof UserCatalogOutputDataInner
     */
    '_count': UserCatalogOutputDataInnerCount;
    /**
     * 
     * @type {string}
     * @memberof UserCatalogOutputDataInner
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof UserCatalogOutputDataInner
     */
    'socialId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserCatalogOutputDataInner
     */
    'picture': string;
    /**
     * 
     * @type {string}
     * @memberof UserCatalogOutputDataInner
     */
    'fullName': string;
    /**
     * 
     * @type {string}
     * @memberof UserCatalogOutputDataInner
     */
    'location': string;
}

