/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ActivityOutput
 */
export interface ActivityOutput {
    /**
     * 
     * @type {string}
     * @memberof ActivityOutput
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof ActivityOutput
     */
    'time': string;
    /**
     * 
     * @type {number}
     * @memberof ActivityOutput
     */
    'importance': number;
}

