/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AdminCatalogOutputDataInnerMajorGenre } from './admin-catalog-output-data-inner-major-genre';
// May contain unused imports in some cases
// @ts-ignore
import { UserAdminCatalogDataInnerSelectedGenresInner } from './user-admin-catalog-data-inner-selected-genres-inner';

/**
 * 
 * @export
 * @interface AdminCatalogOutputDataInner
 */
export interface AdminCatalogOutputDataInner {
    /**
     * 
     * @type {string}
     * @memberof AdminCatalogOutputDataInner
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof AdminCatalogOutputDataInner
     */
    'pages': number;
    /**
     * 
     * @type {number}
     * @memberof AdminCatalogOutputDataInner
     */
    'popularity': number;
    /**
     * 
     * @type {boolean}
     * @memberof AdminCatalogOutputDataInner
     */
    'visible': boolean;
    /**
     * 
     * @type {Array<UserAdminCatalogDataInnerSelectedGenresInner>}
     * @memberof AdminCatalogOutputDataInner
     */
    'genres': Array<UserAdminCatalogDataInnerSelectedGenresInner>;
    /**
     * 
     * @type {AdminCatalogOutputDataInnerMajorGenre}
     * @memberof AdminCatalogOutputDataInner
     */
    'majorGenre': AdminCatalogOutputDataInnerMajorGenre;
    /**
     * 
     * @type {number}
     * @memberof AdminCatalogOutputDataInner
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof AdminCatalogOutputDataInner
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof AdminCatalogOutputDataInner
     */
    'picture': string;
    /**
     * 
     * @type {string}
     * @memberof AdminCatalogOutputDataInner
     */
    'author': string;
}

