/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Activity } from './activity';
// May contain unused imports in some cases
// @ts-ignore
import { CountOutput } from './count-output';
// May contain unused imports in some cases
// @ts-ignore
import { Review } from './review';
// May contain unused imports in some cases
// @ts-ignore
import { ShortGenre } from './short-genre';

/**
 * 
 * @export
 * @interface AdminInfoByIdOutput
 */
export interface AdminInfoByIdOutput {
    /**
     * book id
     * @type {number}
     * @memberof AdminInfoByIdOutput
     */
    'id': number;
    /**
     * book title
     * @type {string}
     * @memberof AdminInfoByIdOutput
     */
    'title': string;
    /**
     * book picture
     * @type {string}
     * @memberof AdminInfoByIdOutput
     */
    'picture': string;
    /**
     * book author
     * @type {string}
     * @memberof AdminInfoByIdOutput
     */
    'author': string;
    /**
     * book created at
     * @type {string}
     * @memberof AdminInfoByIdOutput
     */
    'createdAt': string;
    /**
     * book updated at
     * @type {string}
     * @memberof AdminInfoByIdOutput
     */
    'updatedAt': string;
    /**
     * book visibility
     * @type {boolean}
     * @memberof AdminInfoByIdOutput
     */
    'visible': boolean;
    /**
     * book ebook
     * @type {string}
     * @memberof AdminInfoByIdOutput
     */
    'ebook': string;
    /**
     * book description
     * @type {string}
     * @memberof AdminInfoByIdOutput
     */
    'description': string;
    /**
     * book popularity
     * @type {number}
     * @memberof AdminInfoByIdOutput
     */
    'popularity': number;
    /**
     * book pages
     * @type {number}
     * @memberof AdminInfoByIdOutput
     */
    'pages': number;
    /**
     * book activities
     * @type {Array<Activity>}
     * @memberof AdminInfoByIdOutput
     */
    'activities': Array<Activity>;
    /**
     * book count
     * @type {CountOutput}
     * @memberof AdminInfoByIdOutput
     */
    '_count': CountOutput;
    /**
     * book review
     * @type {Array<Review>}
     * @memberof AdminInfoByIdOutput
     */
    'review': Array<Review>;
    /**
     * 
     * @type {Array<ShortGenre>}
     * @memberof AdminInfoByIdOutput
     */
    'genres': Array<ShortGenre>;
}

