/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AdminInfoByIdOutputReviewInnerUser } from './admin-info-by-id-output-review-inner-user';

/**
 * 
 * @export
 * @interface AdminInfoByIdOutputReviewInner
 */
export interface AdminInfoByIdOutputReviewInner {
    /**
     * 
     * @type {number}
     * @memberof AdminInfoByIdOutputReviewInner
     */
    'id': number;
    /**
     * 
     * @type {Array<string>}
     * @memberof AdminInfoByIdOutputReviewInner
     */
    'tags': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AdminInfoByIdOutputReviewInner
     */
    'text': string;
    /**
     * 
     * @type {number}
     * @memberof AdminInfoByIdOutputReviewInner
     */
    'rating': number;
    /**
     * 
     * @type {AdminInfoByIdOutputReviewInnerUser}
     * @memberof AdminInfoByIdOutputReviewInner
     */
    'user': AdminInfoByIdOutputReviewInnerUser;
}

