/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AuthUserDto } from './auth-user-dto';

/**
 * 
 * @export
 * @interface AuthResponse
 */
export interface AuthResponse {
    /**
     * Access token
     * @type {string}
     * @memberof AuthResponse
     */
    'accessToken': string;
    /**
     * Refresh token
     * @type {string}
     * @memberof AuthResponse
     */
    'refreshToken': string;
    /**
     * type of auth
     * @type {string}
     * @memberof AuthResponse
     */
    'type': string;
    /**
     * User data
     * @type {AuthUserDto}
     * @memberof AuthResponse
     */
    'user': AuthUserDto;
}

