/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AuthResponseDtoUser } from './auth-response-dto-user';

/**
 * 
 * @export
 * @interface AuthResponseDto
 */
export interface AuthResponseDto {
    /**
     * 
     * @type {string}
     * @memberof AuthResponseDto
     */
    'accessToken': string;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseDto
     */
    'refreshToken': string;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseDto
     */
    'type': string;
    /**
     * 
     * @type {AuthResponseDtoUser}
     * @memberof AuthResponseDto
     */
    'user': AuthResponseDtoUser;
}

