/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Book
 */
export interface Book {
    /**
     * Unique identifier for the book
     * @type {number}
     * @memberof Book
     */
    'id': number;
    /**
     * Date when the book was created
     * @type {string}
     * @memberof Book
     */
    'createdAt': string;
    /**
     * Date when the book was last updated
     * @type {string}
     * @memberof Book
     */
    'updatedAt': string;
    /**
     * Title of the book
     * @type {string}
     * @memberof Book
     */
    'title': string;
    /**
     * Author of the book
     * @type {string}
     * @memberof Book
     */
    'author': string;
    /**
     * URL of the picture of the book
     * @type {string}
     * @memberof Book
     */
    'picture': string;
    /**
     * Description of the book
     * @type {string}
     * @memberof Book
     */
    'description': string;
    /**
     * URL of the book
     * @type {string}
     * @memberof Book
     */
    'ebook': string;
    /**
     * Number of pages of the book
     * @type {number}
     * @memberof Book
     */
    'pages': number;
    /**
     * Rating of the book
     * @type {number}
     * @memberof Book
     */
    'popularity': number;
    /**
     * Visibility of the book
     * @type {boolean}
     * @memberof Book
     */
    'visible': boolean;
    /**
     * Major genre of the book
     * @type {object}
     * @memberof Book
     */
    'majorGenre': object;
    /**
     * Minor genres of the book
     * @type {Array<object>}
     * @memberof Book
     */
    'genres': Array<object>;
    /**
     * Reviews of the book
     * @type {Array<object>}
     * @memberof Book
     */
    'review': Array<object>;
    /**
     * Users who have read the book
     * @type {Array<object>}
     * @memberof Book
     */
    'finishedBy': Array<object>;
    /**
     * Users who have saved the book
     * @type {Array<object>}
     * @memberof Book
     */
    'savedBy': Array<object>;
    /**
     * Users who are currently reading the book
     * @type {Array<object>}
     * @memberof Book
     */
    'readingBy': Array<object>;
    /**
     * Activities related to the book
     * @type {Array<object>}
     * @memberof Book
     */
    'activities': Array<object>;
}

