/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EBookType } from './ebook-type';

/**
 * 
 * @export
 * @interface CreateBookDto
 */
export interface CreateBookDto {
    /**
     * book id
     * @type {number}
     * @memberof CreateBookDto
     */
    'id': number;
    /**
     * book title
     * @type {string}
     * @memberof CreateBookDto
     */
    'title': string;
    /**
     * book picture
     * @type {string}
     * @memberof CreateBookDto
     */
    'picture': string;
    /**
     * book author
     * @type {string}
     * @memberof CreateBookDto
     */
    'author': string;
    /**
     * book description
     * @type {string}
     * @memberof CreateBookDto
     */
    'description': string;
    /**
     * book pages
     * @type {number}
     * @memberof CreateBookDto
     */
    'readingTime': number;
    /**
     * book popularity
     * @type {number}
     * @memberof CreateBookDto
     */
    'rating': number;
    /**
     * book visibility
     * @type {boolean}
     * @memberof CreateBookDto
     */
    'visible': boolean;
    /**
     * 
     * @type {Array<EBookType>}
     * @memberof CreateBookDto
     */
    'ebook': Array<EBookType>;
    /**
     * Array of genres
     * @type {Array<number>}
     * @memberof CreateBookDto
     */
    'genres': Array<number>;
}

