/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateBookDtoTestEbookInner } from './create-book-dto-test-ebook-inner';
// May contain unused imports in some cases
// @ts-ignore
import { CreateBookDtoTestGenresInner } from './create-book-dto-test-genres-inner';

/**
 * 
 * @export
 * @interface CreateBookDtoTest
 */
export interface CreateBookDtoTest {
    /**
     * 
     * @type {string}
     * @memberof CreateBookDtoTest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookDtoTest
     */
    'author': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookDtoTest
     */
    'description': string;
    /**
     * 
     * @type {Array<CreateBookDtoTestEbookInner>}
     * @memberof CreateBookDtoTest
     */
    'ebook': Array<CreateBookDtoTestEbookInner>;
    /**
     * 
     * @type {number}
     * @memberof CreateBookDtoTest
     */
    'rating': number;
    /**
     * 
     * @type {string}
     * @memberof CreateBookDtoTest
     */
    'picture': string;
    /**
     * 
     * @type {Array<CreateBookDtoTestGenresInner>}
     * @memberof CreateBookDtoTest
     */
    'genres': Array<CreateBookDtoTestGenresInner>;
}

