/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateRequestEbookInnerChaptersInner } from './create-request-ebook-inner-chapters-inner';

/**
 * 
 * @export
 * @interface CreateRequestEbookInner
 */
export interface CreateRequestEbookInner {
    /**
     * 
     * @type {string}
     * @memberof CreateRequestEbookInner
     */
    'title'?: string;
    /**
     * 
     * @type {Array<CreateRequestEbookInnerChaptersInner>}
     * @memberof CreateRequestEbookInner
     */
    'chapters'?: Array<CreateRequestEbookInnerChaptersInner>;
}

