/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateBookDtoTestEbookInnerChaptersInner } from './create-book-dto-test-ebook-inner-chapters-inner';

/**
 * 
 * @export
 * @interface CreateBookDtoTestEbookInner
 */
export interface CreateBookDtoTestEbookInner {
    /**
     * 
     * @type {string}
     * @memberof CreateBookDtoTestEbookInner
     */
    'title': string;
    /**
     * 
     * @type {number}
     * @memberof CreateBookDtoTestEbookInner
     */
    'id': number;
    /**
     * 
     * @type {Array<CreateBookDtoTestEbookInnerChaptersInner>}
     * @memberof CreateBookDtoTestEbookInner
     */
    'chapters': Array<CreateBookDtoTestEbookInnerChaptersInner>;
}

