/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EBookType } from './ebook-type';

/**
 * 
 * @export
 * @interface CreateBookDto
 */
export interface CreateBookDto {
    /**
     * Title of the book
     * @type {string}
     * @memberof CreateBookDto
     */
    'title': string;
    /**
     * Author of the book
     * @type {string}
     * @memberof CreateBookDto
     */
    'author': string;
    /**
     * Description of the book
     * @type {string}
     * @memberof CreateBookDto
     */
    'description': string;
    /**
     * 
     * @type {Array<EBookType>}
     * @memberof CreateBookDto
     */
    'ebook': Array<EBookType>;
    /**
     * Number of pages in the book
     * @type {number}
     * @memberof CreateBookDto
     */
    'pages': number;
    /**
     * Number of goodRead reviews
     * @type {number}
     * @memberof CreateBookDto
     */
    'popularity': number;
    /**
     * Array of genres
     * @type {Array<number>}
     * @memberof CreateBookDto
     */
    'genres': Array<number>;
    /**
     * 
     * @type {string}
     * @memberof CreateBookDto
     */
    'picture': string;
}

