/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EbookByIdOutputChaptersInner } from './ebook-by-id-output-chapters-inner';

/**
 * 
 * @export
 * @interface EbookByIdOutput
 */
export interface EbookByIdOutput {
    /**
     * 
     * @type {Array<string>}
     * @memberof EbookByIdOutput
     */
    'file': Array<string>;
    /**
     * 
     * @type {Array<EbookByIdOutputChaptersInner>}
     * @memberof EbookByIdOutput
     */
    'chapters': Array<EbookByIdOutputChaptersInner>;
    /**
     * 
     * @type {number}
     * @memberof EbookByIdOutput
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof EbookByIdOutput
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof EbookByIdOutput
     */
    'picture': string;
    /**
     * 
     * @type {string}
     * @memberof EbookByIdOutput
     */
    'author': string;
}

