/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EditBookDto
 */
export interface EditBookDto {
    /**
     * Title of the book
     * @type {string}
     * @memberof EditBookDto
     */
    'title'?: string;
    /**
     * Author of the book
     * @type {string}
     * @memberof EditBookDto
     */
    'author'?: string;
    /**
     * Uploaded picture
     * @type {string}
     * @memberof EditBookDto
     */
    'description'?: string;
    /**
     * Description of the book
     * @type {string}
     * @memberof EditBookDto
     */
    'picture'?: string;
    /**
     * Uploaded ebook
     * @type {string}
     * @memberof EditBookDto
     */
    'ebook'?: string;
    /**
     * Number of pages in the book
     * @type {number}
     * @memberof EditBookDto
     */
    'pages'?: number;
    /**
     * Is book visible
     * @type {boolean}
     * @memberof EditBookDto
     */
    'visible'?: boolean;
    /**
     * Number of goodRead reviews
     * @type {number}
     * @memberof EditBookDto
     */
    'popularity'?: number;
}

