/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EditBookDto
 */
export interface EditBookDto {
    /**
     * 
     * @type {string}
     * @memberof EditBookDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof EditBookDto
     */
    'author': string;
    /**
     * 
     * @type {string}
     * @memberof EditBookDto
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof EditBookDto
     */
    'picture': string;
    /**
     * 
     * @type {string}
     * @memberof EditBookDto
     */
    'ebook': string;
    /**
     * 
     * @type {number}
     * @memberof EditBookDto
     */
    'pages': number;
    /**
     * 
     * @type {number}
     * @memberof EditBookDto
     */
    'popularity': number;
    /**
     * 
     * @type {Array<number>}
     * @memberof EditBookDto
     */
    'genres': Array<number>;
}

