/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserAdminCatalogDataInnerSelectedGenresInner } from './user-admin-catalog-data-inner-selected-genres-inner';
// May contain unused imports in some cases
// @ts-ignore
import { UserLibraryReadingBooksInner } from './user-library-reading-books-inner';

/**
 * 
 * @export
 * @interface FeaturedOutput
 */
export interface FeaturedOutput {
    /**
     * 
     * @type {Array<UserAdminCatalogDataInnerSelectedGenresInner>}
     * @memberof FeaturedOutput
     */
    'relatedGenres': Array<UserAdminCatalogDataInnerSelectedGenresInner>;
    /**
     * 
     * @type {Array<UserLibraryReadingBooksInner>}
     * @memberof FeaturedOutput
     */
    'recommendations': Array<UserLibraryReadingBooksInner>;
    /**
     * 
     * @type {Array<UserLibraryReadingBooksInner>}
     * @memberof FeaturedOutput
     */
    'popularBooks': Array<UserLibraryReadingBooksInner>;
    /**
     * 
     * @type {Array<UserLibraryReadingBooksInner>}
     * @memberof FeaturedOutput
     */
    'bestSellingBooks': Array<UserLibraryReadingBooksInner>;
    /**
     * 
     * @type {Array<UserLibraryReadingBooksInner>}
     * @memberof FeaturedOutput
     */
    'newReleases': Array<UserLibraryReadingBooksInner>;
}

