/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Activity } from './activity';
// May contain unused imports in some cases
// @ts-ignore
import { BookCount } from './book-count';
// May contain unused imports in some cases
// @ts-ignore
import { Review } from './review';
// May contain unused imports in some cases
// @ts-ignore
import { ShortGenre } from './short-genre';

/**
 * 
 * @export
 * @interface FullBook
 */
export interface FullBook {
    /**
     * book slug
     * @type {string}
     * @memberof FullBook
     */
    'slug': string;
    /**
     * book title
     * @type {string}
     * @memberof FullBook
     */
    'title': string;
    /**
     * book picture
     * @type {string}
     * @memberof FullBook
     */
    'picture': string;
    /**
     * book author
     * @type {string}
     * @memberof FullBook
     */
    'author': string;
    /**
     * book description
     * @type {string}
     * @memberof FullBook
     */
    'description': string;
    /**
     * book readingTime
     * @type {number}
     * @memberof FullBook
     */
    'readingTime': number;
    /**
     * book chapters count
     * @type {number}
     * @memberof FullBook
     */
    'chapters': number;
    /**
     * book rating
     * @type {number}
     * @memberof FullBook
     */
    'rating': number;
    /**
     * book visibility
     * @type {boolean}
     * @memberof FullBook
     */
    'isPublic': boolean;
    /**
     * 
     * @type {Array<ShortGenre>}
     * @memberof FullBook
     */
    'genres': Array<ShortGenre>;
    /**
     * book created at
     * @type {string}
     * @memberof FullBook
     */
    'createdAt': string;
    /**
     * book updated at
     * @type {string}
     * @memberof FullBook
     */
    'updatedAt': string;
    /**
     * book ebook
     * @type {string}
     * @memberof FullBook
     */
    'ebook': string;
    /**
     * book count
     * @type {BookCount}
     * @memberof FullBook
     */
    '_count': BookCount;
    /**
     * book activities
     * @type {Array<Activity>}
     * @memberof FullBook
     */
    'activities': Array<Activity>;
    /**
     * book review
     * @type {Array<Review>}
     * @memberof FullBook
     */
    'review': Array<Review>;
}

