/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserCatalogOutputDataInnerSelectedGenresInner } from './user-catalog-output-data-inner-selected-genres-inner';
// May contain unused imports in some cases
// @ts-ignore
import { UserLibraryOutputFinishedBooksInner } from './user-library-output-finished-books-inner';
// May contain unused imports in some cases
// @ts-ignore
import { UserLibraryOutputReadingBooksInnerAuthor } from './user-library-output-reading-books-inner-author';

/**
 * 
 * @export
 * @interface InfoBySlug
 */
export interface InfoBySlug {
    /**
     * 
     * @type {string}
     * @memberof InfoBySlug
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof InfoBySlug
     */
    'readingTime': number;
    /**
     * 
     * @type {number}
     * @memberof InfoBySlug
     */
    'chapters': number;
    /**
     * 
     * @type {number}
     * @memberof InfoBySlug
     */
    'rating': number;
    /**
     * 
     * @type {boolean}
     * @memberof InfoBySlug
     */
    'isPublic': boolean;
    /**
     * 
     * @type {Array<UserCatalogOutputDataInnerSelectedGenresInner>}
     * @memberof InfoBySlug
     */
    'genres': Array<UserCatalogOutputDataInnerSelectedGenresInner>;
    /**
     * 
     * @type {string}
     * @memberof InfoBySlug
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof InfoBySlug
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof InfoBySlug
     */
    'picture': string;
    /**
     * 
     * @type {UserLibraryOutputReadingBooksInnerAuthor}
     * @memberof InfoBySlug
     */
    'author': UserLibraryOutputReadingBooksInnerAuthor;
    /**
     * 
     * @type {Array<UserLibraryOutputFinishedBooksInner>}
     * @memberof InfoBySlug
     */
    'fromSameAuthor': Array<UserLibraryOutputFinishedBooksInner>;
}

