/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OutputChapterChild
 */
export interface OutputChapterChild {
	/**
	 * chapter child name
	 * @type {string}
	 * @memberof OutputChapterChild
	 */
	name: string
	/**
	 * chapter child link
	 * @type {string}
	 * @memberof OutputChapterChild
	 */
	link: string
}
