/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ParserDto
 */
export interface ParserDto {
	/**
	 * url of the parser
	 * @type {string}
	 * @memberof ParserDto
	 */
	url: string
	/**
	 * page of the parser
	 * @type {number}
	 * @memberof ParserDto
	 */
	page: number
}
