/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReactionByBookOutput
 */
export interface ReactionByBookOutput {
    /**
     * 
     * @type {number}
     * @memberof ReactionByBookOutput
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ReactionByBookOutput
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof ReactionByBookOutput
     */
    'text': string;
    /**
     * 
     * @type {string}
     * @memberof ReactionByBookOutput
     */
    'xpath': string;
    /**
     * 
     * @type {number}
     * @memberof ReactionByBookOutput
     */
    'startOffset': number;
    /**
     * 
     * @type {number}
     * @memberof ReactionByBookOutput
     */
    'endOffset': number;
}

