/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReactionDtoUpdateReaction
 */
export interface ReactionDtoUpdateReaction {
    /**
     * 
     * @type {string}
     * @memberof ReactionDtoUpdateReaction
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReactionDtoUpdateReaction
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReactionDtoUpdateReaction
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReactionDtoUpdateReaction
     */
    'text'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReactionDtoUpdateReaction
     */
    'xpath'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReactionDtoUpdateReaction
     */
    'startOffset'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReactionDtoUpdateReaction
     */
    'endOffset'?: number;
}

