/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ShortBook
 */
export interface ShortBook {
    /**
     * book slug
     * @type {string}
     * @memberof ShortBook
     */
    'slug': string;
    /**
     * book title
     * @type {string}
     * @memberof ShortBook
     */
    'title': string;
    /**
     * book picture
     * @type {string}
     * @memberof ShortBook
     */
    'picture': string;
    /**
     * book author
     * @type {string}
     * @memberof ShortBook
     */
    'author': string;
}

