/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Statistics
 */
export interface Statistics {
    /**
     * Users count
     * @type {number}
     * @memberof Statistics
     */
    'users': number;
    /**
     * Books count
     * @type {number}
     * @memberof Statistics
     */
    'books': number;
    /**
     * Authors count
     * @type {number}
     * @memberof Statistics
     */
    'authors': number;
}

