/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserLibraryOutputReadingBooksInnerAuthor } from './user-library-output-reading-books-inner-author';
// May contain unused imports in some cases
// @ts-ignore
import { UserLibraryOutputReadingBooksInnerReadingHistory } from './user-library-output-reading-books-inner-reading-history';

/**
 * 
 * @export
 * @interface UserLibraryOutputReadingBooksInner
 */
export interface UserLibraryOutputReadingBooksInner {
    /**
     * 
     * @type {string}
     * @memberof UserLibraryOutputReadingBooksInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UserLibraryOutputReadingBooksInner
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof UserLibraryOutputReadingBooksInner
     */
    'picture': string;
    /**
     * 
     * @type {UserLibraryOutputReadingBooksInnerAuthor}
     * @memberof UserLibraryOutputReadingBooksInner
     */
    'author': UserLibraryOutputReadingBooksInnerAuthor;
    /**
     * 
     * @type {number}
     * @memberof UserLibraryOutputReadingBooksInner
     */
    'rating': number;
    /**
     * 
     * @type {UserLibraryOutputReadingBooksInnerReadingHistory}
     * @memberof UserLibraryOutputReadingBooksInner
     */
    'readingHistory': UserLibraryOutputReadingBooksInnerReadingHistory | null;
}

