/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserCatalogOutputDataInnerActivitiesInnerActivitiesInner } from './user-catalog-output-data-inner-activities-inner-activities-inner';

/**
 * 
 * @export
 * @interface UserCatalogOutputDataInnerActivitiesInner
 */
export interface UserCatalogOutputDataInnerActivitiesInner {
    /**
     * 
     * @type {string}
     * @memberof UserCatalogOutputDataInnerActivitiesInner
     */
    'date': string;
    /**
     * 
     * @type {number}
     * @memberof UserCatalogOutputDataInnerActivitiesInner
     */
    'count': number;
    /**
     * 
     * @type {number}
     * @memberof UserCatalogOutputDataInnerActivitiesInner
     */
    'level': number;
    /**
     * 
     * @type {Array<UserCatalogOutputDataInnerActivitiesInnerActivitiesInner>}
     * @memberof UserCatalogOutputDataInnerActivitiesInner
     */
    'activities': Array<UserCatalogOutputDataInnerActivitiesInnerActivitiesInner>;
}

