/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserStatisticsProgressByLastWeekMonday } from './user-statistics-progress-by-last-week-monday';

/**
 * 
 * @export
 * @interface UserStatisticsProgressByLastWeek
 */
export interface UserStatisticsProgressByLastWeek {
    /**
     * 
     * @type {UserStatisticsProgressByLastWeekMonday}
     * @memberof UserStatisticsProgressByLastWeek
     */
    'Monday'?: UserStatisticsProgressByLastWeekMonday;
    /**
     * 
     * @type {UserStatisticsProgressByLastWeekMonday}
     * @memberof UserStatisticsProgressByLastWeek
     */
    'Tuesday'?: UserStatisticsProgressByLastWeekMonday;
    /**
     * 
     * @type {UserStatisticsProgressByLastWeekMonday}
     * @memberof UserStatisticsProgressByLastWeek
     */
    'Wednesday'?: UserStatisticsProgressByLastWeekMonday;
    /**
     * 
     * @type {UserStatisticsProgressByLastWeekMonday}
     * @memberof UserStatisticsProgressByLastWeek
     */
    'Thursday'?: UserStatisticsProgressByLastWeekMonday;
    /**
     * 
     * @type {UserStatisticsProgressByLastWeekMonday}
     * @memberof UserStatisticsProgressByLastWeek
     */
    'Friday'?: UserStatisticsProgressByLastWeekMonday;
    /**
     * 
     * @type {UserStatisticsProgressByLastWeekMonday}
     * @memberof UserStatisticsProgressByLastWeek
     */
    'Saturday'?: UserStatisticsProgressByLastWeekMonday;
    /**
     * 
     * @type {UserStatisticsProgressByLastWeekMonday}
     * @memberof UserStatisticsProgressByLastWeek
     */
    'Sunday'?: UserStatisticsProgressByLastWeekMonday;
}

