/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserAdminCatalogDataInnerCount } from './user-admin-catalog-data-inner-count';
// May contain unused imports in some cases
// @ts-ignore
import { UserAdminCatalogDataInnerSelectedGenresInner } from './user-admin-catalog-data-inner-selected-genres-inner';

/**
 * 
 * @export
 * @interface UserAdminCatalogDataInner
 */
export interface UserAdminCatalogDataInner {
    /**
     * 
     * @type {UserAdminCatalogDataInnerCount}
     * @memberof UserAdminCatalogDataInner
     */
    '_count': UserAdminCatalogDataInnerCount;
    /**
     * 
     * @type {Array<UserAdminCatalogDataInnerSelectedGenresInner>}
     * @memberof UserAdminCatalogDataInner
     */
    'selectedGenres': Array<UserAdminCatalogDataInnerSelectedGenresInner>;
    /**
     * 
     * @type {string}
     * @memberof UserAdminCatalogDataInner
     */
    'role': RoleEnum;
    /**
     * 
     * @type {number}
     * @memberof UserAdminCatalogDataInner
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UserAdminCatalogDataInner
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof UserAdminCatalogDataInner
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof UserAdminCatalogDataInner
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserAdminCatalogDataInner
     */
    'socialId': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserAdminCatalogDataInner
     */
    'password': string | null;
    /**
     * 
     * @type {string}
     * @memberof UserAdminCatalogDataInner
     */
    'picture': string;
    /**
     * 
     * @type {string}
     * @memberof UserAdminCatalogDataInner
     */
    'fullName': string;
    /**
     * 
     * @type {string}
     * @memberof UserAdminCatalogDataInner
     */
    'location': string;
}

export const RoleEnum = {
    User: 'user',
    Admin: 'admin'
} as const;

export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];


