/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserAdminCatalogDataInner } from './user-admin-catalog-data-inner';

/**
 * 
 * @export
 * @interface UserAdminCatalog
 */
export interface UserAdminCatalog {
    /**
     * 
     * @type {Array<UserAdminCatalogDataInner>}
     * @memberof UserAdminCatalog
     */
    'data': Array<UserAdminCatalogDataInner>;
    /**
     * 
     * @type {boolean}
     * @memberof UserAdminCatalog
     */
    'canLoadMore': boolean;
    /**
     * 
     * @type {number}
     * @memberof UserAdminCatalog
     */
    'totalPages': number;
}

