/* tslint:disable */
/* eslint-disable */
/**
 * Booknex
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * user role
     * @type {object}
     * @memberof User
     */
    'role': object;
    /**
     * user id
     * @type {number}
     * @memberof User
     */
    'id': number;
    /**
     * user created at
     * @type {string}
     * @memberof User
     */
    'createdAt': string;
    /**
     * user email
     * @type {string}
     * @memberof User
     */
    'email': string;
    /**
     * user social id
     * @type {string}
     * @memberof User
     */
    'socialId': string;
    /**
     * user password
     * @type {string}
     * @memberof User
     */
    'password': string;
    /**
     * user picture
     * @type {string}
     * @memberof User
     */
    'picture': string;
    /**
     * user full name
     * @type {string}
     * @memberof User
     */
    'fullName': string;
    /**
     * user location
     * @type {string}
     * @memberof User
     */
    'location': string;
}

